parameters:
  app.max_file_upload_size: 1048576 # 1MB

services:
  _defaults:
    autowire: true
    autoconfigure: true

  _instanceof:
    App\Service\ArchiverMethod:
      tags: [ 'app.archiver_method' ]

  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Controller\ArchiveController:
    arguments:
      $maxFilesize: '%app.max_file_upload_size%'

  App\Service\ArchiverService:
    arguments:
      $archiverMethods: !tagged_iterator 'app.archiver_method'
